apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
  labels: {
    component: example1
  }
spec:
  replicas: 2
  selector:
    matchLabels:
      component: example1
  template:
    metadata:
      labels:
        component: example1
    spec:
      volumes:
        - name: host-mount
          hostPath:
            path: "/host"
      containers:
        - name: example1
          image: hyperledger/fabric-tools:latest
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - mountPath: /host
              name: host-mount
