apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels: {
    component: api
  }
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
spec:
  type: NodePort
  selector:
    component: api
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
